### ISSUE TITLE
ZeroDivisionErrorが出る

### ISSUE THREAD

**Issue by soukouki** [soukouki/my-calc#4]
`echo "30*(1/0)"| my-calc`

```
>parser.rb.y:39:in `convert': divided by 0 (ZeroDivisionError)
        from parser.rb.y:39:in `Rational'
        from parser.rb.y:39:in `_reduce_10'
        from C:/Ruby23-x64/lib/ruby/2.3.0/racc/parser.rb:259:in `_racc_do_parse_c'
        from C:/Ruby23-x64/lib/ruby/2.3.0/racc/parser.rb:259:in `do_parse'
        from C:/Users/shu-hey/program/my-calc/parser.rb:16:in `parse_preparation'
        from C:/Users/shu-hey/program/my-calc/parser.rb:11:in `parse'
        from C:/Users/shu-hey/program/my-calc.rb:19:in `process'
        from C:/Users/shu-hey/program/my-calc.rb:38:in `<main>'
```

`echo "30*(1/0.0)"| my-calc`の動作と同じになるようにするのが良いと思う。

**Comment by soukouki** [comment]
修正
